apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mc-fse
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 8